name: tanzanian_bms
description: "Comprehensive Business Management System for Tanzanian businesses"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI and State Management
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_adaptive_scaffold: ^0.1.7
  fl_chart: ^0.65.0
  flutter_form_builder: ^9.1.1
  form_builder_validators: 11.1.2
  data_table_2: ^2.5.9
  
  # Database and Storage
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1
  path_provider: ^2.1.2
  cloud_firestore: ^4.13.1
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  sembast: ^3.5.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Connectivity
  connectivity_plus: ^5.0.2
  synchronized: ^3.1.0

  # API and Network
  dio: ^5.4.0
  http: ^1.1.2

  # Authentication and Security
  local_auth: ^2.1.7
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  
  # Image handling
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  
  # PDF and Document
  pdf: ^3.10.7
  printing: ^5.11.1
  open_file: ^3.3.2
  file_picker: ^6.1.1
  
  # Notification and messaging
  flutter_local_notifications: ^16.3.2
  firebase_messaging: ^14.7.4
  
  # Barcode scanning
  mobile_scanner: ^3.5.6
  barcode_widget: ^2.0.4
  
  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  uuid: ^4.2.2
  logger: ^2.0.2+1
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.2
  
  # Animation
  flutter_animate: ^4.3.0
  lottie: ^2.7.0

  # ML and AI
  tflite_flutter: ^0.10.3
  ml_algo: ^16.17.8
  dropdown_button2: ^2.3.9
  syncfusion_flutter_charts: ^29.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
